Enum.LOG_LEVEL_NONE = "NONE";
Enum.LOG_LEVEL_TEST = "TEST";
Enum.LOG_LEVEL_DEBUG = "DEBUG";
Enum.LOG_LEVEL_INFO = "INFO";
Enum.LOG_LEVEL_NOTICE = "NOTICE";
Enum.LOG_LEVEL_WARNING = "WARNING";
Enum.LOG_LEVEL_ERROR = "ERROR";
Enum.LOG_LEVEL_CRITICAL = "CRITICAL";
Enum.LOG_LEVEL_ALERT = "ALERT";
Enum.LOG_LEVEL_EMERGENCY = "EMERGENCY";
Enum.LOG_LEVEL_SERVER = "SERVER";
Enum.LOG_LEVEL_PROFILE = "PROFILE";

// TODO Move
Enum.FRAME_STRATA_OVERLAY = 10000;
