const WIDGET_TEMPLATE_WINDOW = "Window";
const WIDGET_TEMPLATE_WINDOW_TITLEBAR = "WindowTitle";
const WIDGET_TEMPLATE_WINDOW_MINIMIZEBUTTON = "WindowTitleMinimizeButton";
const WIDGET_TEMPLATE_WINDOW_MAXIMIZEBUTTON = "WindowTitleMaximizeButton";
const WIDGET_TEMPLATE_WINDOW_CLOSEBUTTON = "WindowTitleCloseButton";
const WIDGET_TEMPLATE_WINDOW_CONTENTPANE = "WindowContent";
const WIDGET_TEMPLATE_WINDOW_STATUSBAR = "WindowStatusBar";
