Enum.WIDGET_TEMPLATE_WINDOW = "Window";
Enum.WIDGET_TEMPLATE_WINDOW_TITLEBAR = "WindowTitle";
Enum.WIDGET_TEMPLATE_WINDOW_MINIMIZEBUTTON = "WindowTitleMinimizeButton";
Enum.WIDGET_TEMPLATE_WINDOW_MAXIMIZEBUTTON = "WindowTitleMaximizeButton";
Enum.WIDGET_TEMPLATE_WINDOW_CLOSEBUTTON = "WindowTitleCloseButton";
Enum.WIDGET_TEMPLATE_WINDOW_CONTENTPANE = "WindowContent";
Enum.WIDGET_TEMPLATE_WINDOW_STATUSBAR = "WindowStatus";
