const LocalizationOptionsSchema = JOI.object({
	activeLocale: JOI.string()
		.required()
		.valid(
			WEBCLIENT_LOCALE_STRING_ENGLISH,
			WEBCLIENT_LOCALE_STRING_GERMAN,
			WEBCLIENT_LOCALE_STRING_FRENCH,
			WEBCLIENT_LOCALE_STRING_SPANISH,
			WEBCLIENT_LOCALE_STRING_RUSSIAN,
			WEBCLIENT_LOCALE_STRING_CHINESE_SIMPLIFIED,
			WEBCLIENT_LOCALE_STRING_CHINESE_TRADITIONAL,
			WEBCLIENT_LOCALE_STRING_ITALIAN,
			WEBCLIENT_LOCALE_STRING_KOREAN,
			WEBCLIENT_LOCALE_STRING_PORTUGUESE
		),
});
