const WEBCLIENT_DEFAULT_LOCALE = Enum.WEBCLIENT_LOCALE_STRING_ENGLISH;
var WEBCLIENT_ACTIVE_LOCALE = Enum.WEBCLIENT_LOCALE_STRING_ENGLISH;

// Defines which localization tables (JSON) should be loaded when the client is started
const WEBCLIENT_SUPPORTED_LOCALES = {
	[Enum.WEBCLIENT_LOCALE_STRING_ENGLISH]: true,
	[Enum.WEBCLIENT_LOCALE_STRING_GERMAN]: true,
	[Enum.WEBCLIENT_LOCALE_STRING_FRENCH]: true,
	[Enum.WEBCLIENT_LOCALE_STRING_SPANISH]: true,
	[Enum.WEBCLIENT_LOCALE_STRING_RUSSIAN]: true,
	[Enum.WEBCLIENT_LOCALE_STRING_CHINESE_SIMPLIFIED]: true,
	[Enum.WEBCLIENT_LOCALE_STRING_CHINESE_TRADITIONAL]: true,
	[Enum.WEBCLIENT_LOCALE_STRING_ITALIAN]: true,
	[Enum.WEBCLIENT_LOCALE_STRING_KOREAN]: true,
	[Enum.WEBCLIENT_LOCALE_STRING_PORTUGUESE]: true,
};
