var WEBCLIENT_ENABLE_LOGGING = true;
var WEBCLIENT_ACTIVE_LOGGERS = {
	[Enum.LOG_LEVEL_NONE]: true,
	[Enum.LOG_LEVEL_TEST]: true,
	[Enum.LOG_LEVEL_INFO]: true,
	[Enum.LOG_LEVEL_DEBUG]: true,
	[Enum.LOG_LEVEL_NOTICE]: true,
	[Enum.LOG_LEVEL_WARNING]: true,
	[Enum.LOG_LEVEL_SERVER]: true,
	[Enum.LOG_LEVEL_CRITICAL]: true,
};
var WEBCLIENT_ENABLE_PROFILING = true;
