name: Formatting

on:
  push:

jobs:
  lint:
    name: prettier
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repo sitory
        uses: actions/checkout@v1

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: Install development dependencies
        run: npm install --also=dev

      - name: Check for inconsistent formatting
        run: npm run check-format
