name: Automated Testing

on:
  pull_request:
    paths-ignore:
      - "README.md"
    types: [opened, synchronize, reopened, ready_for_review]
  push:
    branches:
      - main
    paths-ignore:
      - "README.md"

jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      max-parallel: 6
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        include:
          - os: windows-latest
            ubuntu-workaround-prefix-string: ""
          - os: macos-latest
            ubuntu-workaround-prefix-string: ""
          - os: ubuntu-latest
            ubuntu-workaround-prefix-string: export DISPLAY=:45 && xvfb-run --server-num 45
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: Install development dependencies
        run: npm install --also=dev

      - name: Run automated tests (main thread)
        run: ${{ matrix.ubuntu-workaround-prefix-string }} npm run test-main

      - name: Run automated tests (render thread)
        run: ${{ matrix.ubuntu-workaround-prefix-string }} npm run test-render
